### ISSUE TITLE
Blog: It has come to my attention recently that zfs has been added a new backend for docker.

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/atomic-site#142]
I received a bug report that it was not working with SELinux.   [Turns out there was a simple fix which should get into docker-1.7 or docker-1.8 to fully support labeling within a docker container using the ZFS back end.](https://github.com/docker/docker/issues/13858)

Sadly [ZFS](http://zfsonlinux.org/) can not be merged into the Linux kernel because of Licensing issues.  But if you are willing to use loadable kernel modules you can now run your containers on ZFS with SELinux enforcement.

**Comment by Mic92** [comment]
Some distributions like ubuntu, archlinux, debian have well maintained zfs packages from third-party sources (ubuntu/debian is maintained by the zfsonlinux community itself). There is a rumor, that it could get integrated into debian in the next release, so it would just a another optional kernel module like vboxdrv for virtualbox.

**Comment by rhatdan** [comment]
@Mic92 Thanks, I did not know, probably should add as information.  I put this in as a suggested blog for projectatomic

**Comment by jzb** [comment]
@rhatdan was there a longer post somewhere on this?

**Comment by rhatdan** [comment]
Looks like it has been there for a while.  Googling around found this.

**Comment by rhatdan** [comment]
https://github.com/docker/docker/pull/2995

**Comment by rhatdan** [comment]
This little snippet never got published.  Could we throw it in the blog?

**Comment by jberkus** [comment]
Reviewing old issues.  I don't see an actual blog post above.  Was there one somewhere else?

**Comment by jberkus** [comment]
Closing.
