### ISSUE TITLE
Broken / Incorrect link on Atomic App documentation page.

### ISSUE THREAD

**Issue by pradeepto** [projectatomic/atomic-site#225]
The link to "Nulecule examples directory" on http://www.projectatomic.io/docs/atomicapp/ under the section named"What is Atomic App?" is broken.It points to https://github.com/projectatomic/nulecule/tree/master/examples.

The correct link perhaps is https://github.com/projectatomic/nulecule-library

**Comment by jzb** [comment]
@pradeepto any chance you could put together a directory / page explaining those and then we can link off to the github?

**Comment by pradeepto** [comment]
@jzb Do you mean write a short description about https://github.com/projectatomic/nulecule-library or each of the example application listed on that page.

Or just expanding the https://github.com/projectatomic/nulecule-library/blob/master/README.md is suffice? Although it looks ok to me since each of those application have their own READMEs.

**Comment by jzb** [comment]
A short description that explains the general set would be good, I think.

**Comment by jberkus** [comment]
Link fixed on atomic-site.  Issue about no directory in nulecule-library remains unresolved.  I've opened an issue in that project for it: https://github.com/projectatomic/nulecule-library/issues/76
