### ISSUE TITLE
Broken link http://www.projectatomic.io/docs/atomicapp/Providers.asciidoc

### ISSUE THREAD

**Issue by tnozicka** [projectatomic/atomic-site#255]
Page http://www.projectatomic.io/docs/atomicapp/Providers.asciidoc does not exist.

From page: http://www.projectatomic.io/docs/atomicapp/ under "Provider description".

**Comment by jberkus** [comment]
On 03/07/2016 07:38 AM, Tomáš Nožička wrote:
> Page http://www.projectatomic.io/docs/atomicapp/Providers.asciidoc does
> not exist.
>
>  From page: http://www.projectatomic.io/docs/atomicapp/ under "Provider
> description".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/projectatomic/atomic-site/issues/255>.Web Bug from
> https://github.com/notifications/beacon/AAHBykG5nlMHar6lOc2j1UTPMxi9jNWsks5prEaEgaJpZM4Hq4nD.gif

Please file a bug with atomicapp.  The reason why the link is broken is 
that the doc is missing.

-- 
--
Josh Berkus
Red Hat OSAS
(any opinions are my own)

**Comment by dustymabe** [comment]
Hey @jberkus.. I'm a bit confused. The link is not to the Atomic App GH repo. It is to a page on projectatomic.io. 

If you did want to link to an Atomic App doc then I would suggest this one maybe: https://github.com/projectatomic/atomicapp/blob/master/docs/providers.md

**Comment by dustymabe** [comment]
@jberkus ping

**Comment by jberkus** [comment]
thanks for the link, will copy that over.

**Comment by jberkus** [comment]
So the providers doc isn't intended to be used on its own; it's tied together with the full AtomicApp docs, which are waiting on docs.projectatomic.io to go live.  I'll open an issue there, but for now the link will link the github repo.

**Comment by jberkus** [comment]
Temporary fix pushed.  Closing.
