### ISSUE TITLE
figure out how to transition/link docs dir over to docs subdomain

### ISSUE THREAD

**Issue by jberkus** [projectatomic/atomic-site#267]
Now that we have docs.projectatomic.io, we want to move *all* docs to it.  However, we don't want to break everyone's links.  Ideas on how to make redirects work for individual doc pages?

**Comment by tigert** [comment]
@mscherer might be able to do some server-side redirection for the existing docs? 

Do you plan to keep everything as close to what they are (projectatomic.io/docs/foo -> docs.projectatomic.io/foo) or do you also plan to reorganize the docs content while you do the move?

**Comment by mscherer** [comment]
I am not sure I can't, that's openshift, I do not have access to everything, quite the contrary. 

It has to be done by a .htaccess IIRC.

**Comment by bexelbie** [comment]
We could do a limited time "poor-man's" redirect and create the entire tree with redirect URLs preceeded by a note about deprecation.

@jberkus where is hte issue to track the build out of docs.pa.io?

**Comment by jberkus** [comment]
@tigert, @mscherer I don't really plan to reorganize, since that would involve a lot of link-patching.  I'd rather just move stuff over.

So ... this is the sort of multi-item task which is better handled by kanboard/trello than on github issues, since it has many parts.  Let me set something up.

**Comment by jberkus** [comment]
This issue was moved to projectatomic/docs.projectatomic.io#4
