### ISSUE TITLE
Publish Atomic Registry docs nightly

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomic-site#268]
Documentation for Atomic Registry is being developed based on the [OpenShift Docs repo](https://github.com/openshift/openshift-docs). We want to publish these nightly from the master branch at [docs.projectatomic/registry](#)

Same request as #251 
cc @jlebon

**Comment by jlebon** [comment]
If you can give me the exact build procedure (hopefully only requiring a `docker run`), it should be easy to just tack it on to the best practices job.

**Comment by jberkus** [comment]
This issue was moved to projectatomic/docs.projectatomic.io#1
