### ISSUE TITLE
Few things broken with docs.projectatomic.io as well as registry documentation

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomic-site#301]
Clicking quick start on http://www.projectatomic.io/registry/ brings me http://docs.projectatomic.io/registry/latest/registry_quickstart/index.html to which makes the first three links on the sidebar not work (get started, documentation and developer community)

Under http://docs.projectatomic.io/registry/latest/install_config/syncing_groups_with_ldap.html where it says: "LDAP Client Configuration" the formatting is very hard to read (purple key names, light red key values) There are a few other places where this is happening too.

**Comment by jberkus** [comment]
@cdrage, lthose links are an issue with docs.projectatomic.io, so re-opening over there.

@aweiteka see above on formatting.

**Comment by aweiteka** [comment]
> the first three links on the sidebar not work

Pending fix in https://github.com/openshift/openshift-docs/pull/1883

> the formatting is very hard to read (purple key names, light red key values) There are a few other places where this is happening too.

Known issue. I'm not sure the best approach to resolve this. It occurs when `[source,yaml]` syntax highlighting is used in the asciidoc markup, assuming white background; projectatomic.io styling is black.

**Comment by aweiteka** [comment]
Half of this is fixed with https://github.com/openshift/openshift-docs/pull/1883 (merged)
