### ISSUE TITLE
Blog Post for Docker Brno Meetup - 15 June 2016

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/atomic-site#327]
Draft is here - and needs review please:

PR will come tomorrow (Friday 17 June).  I will be traveling and out of pocket from 18 June so I need to get this to a point where it can be merged easily.

http://etherpad.osuosl.org/4tlMydVGzp

Open Issues:

1 - I need a place to post some slides from one of the speakers.  Can I put them into this repo?  

2 - I need to put some pictures into this post. @eliskasl is going to provide some when she gets them off of her camera.

@jberkus @jzb @bproffitt

**Comment by jberkus** [comment]
Bex,

1 - Sure, if you have the speakers' permission, and the file isn't huge.  If it's a big file, maybe Dropbox?

2 - OK.

**Comment by bexelbie** [comment]
I have the speakers permission.  The file will be included in the PR.  I will be traveling and not able to make future edits.  I have faith in the edits you all suggest and trust you with regards to timing of the post.

I have marked it unpublished to make management easier.
