### ISSUE TITLE
"Running the atomic.app" steps not working 

### ISSUE THREAD

**Issue by budhrg** [projectatomic/atomic-site#341]
Hi,

I was going through building the site and found the "Running the atomic.app" steps are not working for me.

I did all necessary steps mentioned in [First time setup](https://github.com/projectatomic/atomic-site/blob/master/BUILD.md#first-time-setup). 
I am getting some kind of info not error.

```
# answers.conf
➜  atomic-site git:(master) ✗ cat Nulecule/answers.conf
[atomic-site]
datadir = /home/budhram/redhat/atomic-site/data
hostport = 4567
sourcedir = /home/budhram/redhat/atomic-site/source 
image = jberkus/atomic-site
provider = kubernetes
[general]
namespace = default
provider = kubernetes

➜  atomic-site git:(master) ✗ sudo atomicapp run Nulecule 
[INFO] - main.py - Action/Mode Selected is: run
[INFO] - kubernetes.py - Using namespace default
[INFO] - kubernetes.py - trying kubectl at /usr/bin/kubectl
[INFO] - kubernetes.py - found kubectl at /usr/bin/kubectl
[INFO] - kubernetes.py - Deploying to Kubernetes

Your application resides in Nulecule
Please use this directory for managing your application
```

Anything wrong in my setup?

**Comment by jberkus** [comment]
First question: do you have kubernetes installed and running on your system?

If not, you need to change the provider to "docker".

**Comment by budhrg** [comment]
@jberkus : I do not have Kubernetes server runnig in my machine but found client in /usr/bin/kubectl. 

Replacing with docker works fine with this issue https://github.com/projectatomic/atomic-site/issues/343.

I am curious, how message `kubernetes.py - Deploying to Kubernetes` could be executed if server is not found.
```
....
[INFO] - kubernetes.py - found kubectl at /usr/bin/kubectl               
.... IMO we should server is present or not then following steps        
[INFO] - kubernetes.py - Deploying to Kubernetes           
```
