### ISSUE TITLE
Update to Fedora 25

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/atomic-site#381]
The docker file is [based on f23](https://github.com/projectatomic/atomic-site/blob/92b9c890a54fe18ed991d0333fc0a3c34df77d0f/Dockerfile#L1) which is about to be EOL. If the blog is also running on F23 we should migrate them both.

**Comment by jberkus** [comment]
We're still getting errors when we use current Ruby for this.  Attn @mscherer 

Thread.exclusive is deprecated, use Mutex
/usr/local/share/gems/gems/middleman-livereload-3.4.2/lib/middleman-livereload/reactor.rb:21:in `logger'
/usr/local/share/gems/gems/middleman-livereload-3.4.2/lib/middleman-livereload/reactor.rb:59:in `block (4 levels) in start_threaded_reactor'
/usr/local/share/gems/gems/em-websocket-0.5.1/lib/em-websocket/connection.rb:18:in `trigger_on_message'
/usr/local/share/gems/gems/em-websocket-0.5.1/lib/em-websocket/message_processor_06.rb:52:in `message'
/usr/local/share/gems/gems/em-websocket-0.5.1/lib/em-websocket/framing07.rb:118:in `process_data'
/usr/local/share/gems/gems/em-websocket-0.5.1/lib/em-websocket/handler.rb:47:in `receive_data'
/usr/local/share/gems/gems/em-websocket-0.5.1/lib/em-websocket/connection.rb:76:in `receive_data'
/usr/local/share/gems/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
/usr/local/share/gems/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
/usr/local/share/gems/gems/middleman-livereload-3.4.2/lib/middleman-livereload/reactor.rb:44:in `block in start_threaded_reactor'

**Comment by mscherer** [comment]
The blog is built on Centos 7, so that's not a issue. However, I can take a look and update the Docker file

**Comment by jberkus** [comment]
@mscherer that error happens when you try to run Middleman on F25.  That's why I pinged you.

**Comment by mscherer** [comment]
Yup, I did a build but I am not sure if that's a error or harmess message, since the container seems to run (but as it took too long to build, i went to meetings).

But I guess we should maybe just refresh the gem list.

**Comment by FireDrunk** [comment]
I've found several issues with trying to deploy a bare metal Fedora Atomic Host on Feodora 25 via Kickstart.
It seems that the ostree repo's are not updated to f25, but the example files are.

Another thing is that the kickstart example file contains errors regarding the ssh key.

Example file:
```
lang en_US.UTF-8
keyboard us
timezone America/New_York
zerombr
clearpart --all --initlabel
autopart
# sudo user with an ssh key (use your key)
user --name=atomic --groups=wheel --sshkey="ssh-rsa AAAAB3NzaC1yc2EAAAA ..."

# NOTICE: This will download the content from upstream; this will be very slow.
# Create your own OSTree repo locally and mirror the content instead.
ostreesetup --nogpg --osname=fedora-atomic --remote=fedora-atomic --url=https://dl.fedoraproject.org/pub/fedora/linux/atomic/25/ --ref=fedora-atomic/f25/x86_64/docker-host
```

My current file:

```
lang en_US.UTF-8
keyboard us
timezone Europe/Amsterdam
zerombr
clearpart --all --initlabel
autopart
# sudo user with an ssh key (use your key)
user --name=atomic --groups=wheel --sshkey="<key>"

# NOTICE: This will download the content from upstream; this will be very slow.
# Create your own OSTree repo locally and mirror the content instead.
ostreesetup --nogpg --osname=fedora-atomic --remote=fedora-atomic --url=https://dl.fedoraproject.org/pub/fedora/linux/atomic/25/ --ref=fedora-atomic/f25/x86_64/docker-host
```

I still get an error from the ostreesetup command inside the installation that there is no such ref for the docker-host branch in f25.

Also the --sshkey option for user doesn't exist in the kickstart docs: 
https://docs.fedoraproject.org/en-US/Fedora//html/Installation_Guide/sect-kickstart-commands-user.html

**Comment by mscherer** [comment]
@FireDrunk I think this is not related to what we are discussing, as we are speaking of the build of the website. Could you open a separate bug report for that issue ?

**Comment by jberkus** [comment]
@FireDrink: huh, I thought I removed --sshkey; that was supposed to be in 25 and somehow wasn't.  Will look ...

**Comment by jberkus** [comment]
@FireDrunk, I've opened a new bug for your report so that I can track it accurately.

**Comment by mscherer** [comment]
So, the system got changed to build on a F26 container, I am closing this bug.
