### ISSUE TITLE
Purple text on on dark gray in YAML code is difficult to read

### ISSUE THREAD

**Issue by chlunde** [projectatomic/atomic-site#387]
See http://docs.projectatomic.io/registry/latest/registry_quickstart/administrators/system_configuration.html#registry-configuration

    color:#606
    background-color:rgba(0,0,0,0.8)

![screenshot from 2016-12-12 12-43-45](https://cloud.githubusercontent.com/assets/131994/21098257/a5a002ec-c068-11e6-9fb2-9a7c4f97ff67.png)

**Comment by jberkus** [comment]
Ah, was being confused by this, since the source is in another repo.  Will find it.

**Comment by chlunde** [comment]
I think this documentation has been removed from projectatomic.io, so I'm closing this.
