### ISSUE TITLE
Create Blog post on Automating of Building Atomic Host

### ISSUE THREAD

**Issue by trishnaguha** [projectatomic/atomic-site#400]
I am currently working on Automating of Building Atomic host.
Git repo is here https://github.com/trishnaguha/build-atomic-host
The repo is still going through improvement. 

I think it would make sense to have blog post on this after the repository is ready.
Thoughts?

**Comment by jberkus** [comment]
Yes, of course!  I think we need more than a blog post, we need full docs.  I'll work with you on that.

**Comment by trishnaguha** [comment]
@jberkus Thanks! I'm doing some improvement on the repo. You may want to look in to it.

**Comment by lobocode** [comment]
Great job!
It would be interesting to also adapt to CentOs and have a special affection for him. CentOs still attracts more personnel who works with servers (for being a faithful copy to RHEL). I feel that the community is with a bit of difficulty to adapt, install, provision services on it.

**Comment by trishnaguha** [comment]
@lobocode I will give it a try on CentOS. May we can have separate directory for `CentOS` in the Git repo  https://github.com/trishnaguha/build-atomic-host . Feel free to open an issue there.
