### ISSUE TITLE
Getting started guide is wrong

### ISSUE THREAD

**Issue by pastukhov** [projectatomic/atomic-site#406]
Hello!
I'm trying to reproduce [Project Atomic Getting Started Guide](http://www.projectatomic.io/docs/gettingstarted/) and getting ```access denied``` when enabling kube-apiserver service with ```systemctl enable kube-apiserver```
Plase update docs.
I'm using centos-atomic.

**Comment by lobocode** [comment]
Current versions of CentOS Atomic have the kubernetes-master pkg removed from the image, to be run from containers. There's info on that here: https://wiki.centos.org/SpecialInterestGroup/Atomic/ContainerizedMaster.

**Comment by pastukhov** [comment]
Do you have any plans to write Getting started guide against CentOS version?

**Comment by lobocode** [comment]
@pastukhov 
Not's necessarily write a documentation for CentOS, but, instead, to adapt the current documentation for changes of CentOs too. It's possible to reuse what already is done.  I'm working on it!

**Comment by BubacarrC** [comment]
@pastukhov did you managed to solved this issue? I'm trying to replicate the same procedure http://www.projectatomic.io/docs/gettingstarted/ on Centos-Atomic  but I'm getting access denied when I hit I hit this commands **sudo systemctl enable etcd kube-apiserver kube-controller-manager kube-scheduler**

Any clue?

**Comment by pastukhov** [comment]
@BubacarrC Did you make units as described in https://wiki.centos.org/SpecialInterestGroup/Atomic/ContainerizedMaster ?

**Comment by BubacarrC** [comment]
Yes, I made the units and the containers starts to run on my master. However, my nodes are unresponsive when I perform this step on them in forming the cluster. This is my latest issue now. `kubectl get node` list the nodes and they are on the ready state anyways. Any idea?
![screenshot from 2017-06-03 01-33-06](https://cloud.githubusercontent.com/assets/17242111/26748303/c76d1e66-47fc-11e7-9d7f-92bc4b52fd52.png)

**Comment by jasonbrooks** [comment]
You should only need to make those units if you're running centos -- the screen above suggests fedora?

**Comment by BubacarrC** [comment]
Yes, I made the units and the containers starts to run on my master. However, my nodes are unresponsive when I perform this step on them in forming the cluster. This is my latest issue now. `kubectl get node` list the nodes and they are on the ready state anyways. Any idea?
![screenshot from 2017-06-03 01-33-06](https://cloud.githubusercontent.com/assets/17242111/26748303/c76d1e66-47fc-11e7-9d7f-92bc4b52fd52.png)

**Comment by BubacarrC** [comment]
Actually the screenshot was taken from the documentation [here](http://www.projectatomic.io/docs/gettingstarted/) which I'm following. I got issues on that step while trying to form a kubernetes cluster on Centos Atomic distribution.
