### ISSUE TITLE
Blog Post: Contribute to Atomic host Documentation

### ISSUE THREAD

**Issue by trishnaguha** [projectatomic/atomic-site#420]
Project Atomic host Documentation Repo: https://github.com/projectatomic/atomic-host-docs
The post will describe how to write and build Doc using AsciiDoc and encourage community to contribute to the Documentation project.

**Comment by jberkus** [comment]
Cool, are you going to write this?

**Comment by trishnaguha** [comment]
@jberkus Yes.
