### ISSUE TITLE
Run "rpm-ostree install kubernetes-master --reboot" fail.

### ISSUE THREAD

**Issue by warmchang** [projectatomic/atomic-site#430]
According to the document actions (https://github.com/projectatomic/atomic-site/blob/master/source/docs/kubernetes.md), run "rpm-ostree install kubernetes-master --reboot", but got the failure.

> [root@localhost ~]# rpm-ostree install kubernetes-master --reboot
> Checking out tree 91fe03f... done
> 
> Downloading metadata: [=================================================================================================================================================] 100%
> Resolving dependencies... done
> Overlaying... done
> Writing rpmdb... error: Error running transaction: file /usr/bin/hyperkube from install of kubernetes-master-1.5.2-0.5.gita552679.el7.x86_64 conflicts with file from kubernetes-client-1.5.2-0.2.gitc55cf2b.el7.x86_64
> file /usr/bin/hyperkube from install of kubernetes-master-1.5.2-0.5.gita552679.el7.x86_64 conflicts with file from kubernetes-node-1.5.2-0.2.gitc55cf2b.el7.x86_64
> [root@localhost ~]#
> [root@localhost ~]# uname -a
> Linux localhost.localdomain 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> [root@localhost ~]# cat /etc/redhat-release
> CentOS Linux release 7.3.1611 (Core)
> [root@localhost ~]# cat /proc/version
> Linux version 3.10.0-514.10.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Fri Mar 3 00:04:05 UTC 2017
> [root@localhost ~]#

**Comment by jberkus** [comment]
tagging @jasonbrooks

**Comment by jasonbrooks** [comment]
@warmchang The problem here is that the latest kube available in the centos repos is a bit newer at the moment than what's in the image (we'll have an updated tree out soon). In the mean time, you can do `rpm-ostree install kubernetes-master-1.5.2-0.5.gita552679.el7.x86_64 --reboot` to get the master version that matches the node version in the host.

Actually, looking back at your comment, I can see that you were experiencing this same issue, but with different host/pkg versions. The centos repos always get updated a bit before the atomic tree does, so this is a recurring thing.

**Comment by warmchang** [comment]
@jasonbrooks , I understand, thank your for your replay. :smile: 

> [root@localhost ~]# rpm-ostree status
> State: idle
> Deployments:
> ● centos-atomic-host:centos-atomic-host/7/x86_64/standard
>              Version: 7.20170428 (2017-06-06 13:48:44)
>           BaseCommit: 67c8af37c5d05bb3b377ec1bd3c127f98664d6f7a78bf2089fcfb02784d12fbd
>               Commit: eb924ff4f0eb3674ea8c3e3a3c7979c20065befa58a5b3405c8aa2fb4e69a447
>               OSName: centos-atomic-host
>         GPGSignature: 1 signature
>                       Signature made Wed 10 May 2017 05:43:07 AM CST using RSA key ID F17E745691BA8335
>                       Good signature from "CentOS Atomic SIG <security@centos.org>"
>      LayeredPackages: kubernetes-master kubernetes-master-1.5.2-0.5.gita552679.el7.x86_64
> 
>   centos-atomic-host:centos-atomic-host/7/x86_64/standard
>              Version: 7.20170428 (2017-06-06 13:31:03)
>           BaseCommit: 67c8af37c5d05bb3b377ec1bd3c127f98664d6f7a78bf2089fcfb02784d12fbd
>               Commit: 1169ce5e3de95059e438ec63bc6f09d7d899ecc5249503729d62c3856b8588ce
>               OSName: centos-atomic-host
>         GPGSignature: 1 signature
>                       Signature made Wed 10 May 2017 05:43:07 AM CST using RSA key ID F17E745691BA8335
>                       Good signature from "CentOS Atomic SIG <security@centos.org>"
>      LayeredPackages: kubernetes-master-1.5.2-0.5.gita552679.el7.x86_64
> [root@localhost ~]#
