### ISSUE TITLE
Spam on http://ask.projectatomic.io/

### ISSUE THREAD

**Issue by rbu** [projectatomic/atomic-site#494]
The forum is so full of spam it's unusable. There is several topics that are just spam and most of the replies to existing questions are also spam.

**Comment by jberkus** [comment]
Yah, Ask is shutting down at the end of the year.

**Comment by mscherer** [comment]
So ask got removed on the website as part of https://github.com/projectatomic/atomic-site/pull/501 

What are the next step, can I shutdown the server ?

**Comment by sanjacloud** [comment]
From my side yes, but @jberkus might have a reason why not?

**Comment by jberkus** [comment]
nope.  What answers are there are out-of-date and also not very googleable.

**Comment by mscherer** [comment]
Do we want some redirect or something, or a timeline to say "this is deprecated" ? Or a blog post to announce it ?

**Comment by sanjacloud** [comment]
We'll tackle this in a summary blog post after New Year's and mention it as a change item.

**Comment by sanjacloud** [comment]
With how many change have happened: @mscherer please just shut ask down.
