### ISSUE TITLE
Remove Nulecule / Atomic App

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomic-site#511]
Both Nulecule and Atomic App are defunct / unmaintained projects.

We should remove these references / any documentation from the Project Atomic site as we see more increased traffic from the CoreOS announcement.

ping @jberkus @jasonbrooks

**Comment by dustymabe** [comment]
yeah - @sanjacloud is working on revamping our site.

**Comment by sanjacloud** [comment]
Revamping the site, but deleted references anyway already.

**Comment by mscherer** [comment]
Could we somehow keep mention on "we did deprecate them". It kinda feel 1984 to change history, and sometime, people might want to know what happened.

**Comment by sanjacloud** [comment]
@mscherer I'll announce that with the revamp of the website mid-February that we changed some things, it's basically like a new project and fits in with the recent other changes Red Hat as a whole have made. Agree with what you said.
