### ISSUE TITLE
Add announcement that Red Hat bought CoreOS?

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomic-site#512]
We should add a small announcement on the page that we bought it / what it means to Project Atomic.

**Comment by cdrage** [comment]
@jberkus @jasonbrooks

**Comment by jberkus** [comment]
@sanjacloud 

At this point, I don't think anyone knows that it means to Project Atomic?

**Comment by sanjacloud** [comment]
We have a blog post like this in planning but it's fair to say we'll wait with anything for a bit because all we can say is "we don't know anything". We might paraphrase it but I'd say target audience doesn't really like euphemisms for "we don't know" either.

**Comment by jasonbrooks** [comment]
+1 to waiting until we have something to say
