### ISSUE TITLE
Possible migration guides from Container Linux.

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomic-site#513]
Lot's of users are going to be looking at alternatives... Is it possible to add a migration guide to Project Atomic from CoreOS?

**Comment by cdrage** [comment]
@jberkus @jasonbrooks

**Comment by jberkus** [comment]
Given today's news, I think we should maybe hold off on that ...

**Comment by sanjacloud** [comment]
Definitely holding off on that - we don't know what the future holds exactly and most likely we'll have a product that integrates the best of both worlds down the line. We should communicate this as positively as it actually is.
