### ISSUE TITLE
Add License info to all README files

### ISSUE THREAD

**Issue by vincentmayers** [projectatomic/atomic-site#52]
need to add license info to all README files and also a document in each repo

**Comment by stevesmename** [comment]
yes, please. +1

**Comment by jzb** [comment]
Just to be clear you're asking about license info for the repos under projectatomic, not so much the atomic-site?

**Comment by stevesmename** [comment]
Nope, looking for the license file for the atomic-site project. I would
personally like to use a very similar site structure.

On Tue, Jan 27, 2015 at 6:39 AM, jzb <notifications@github.com> wrote:

> Just to be clear you're asking about license info for the repos under
> projectatomic, not so much the atomic-site?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/projectatomic/atomic-site/issues/52#issuecomment-71648537>
> .
>



-- 
Steve Douglas

**Comment by jberkus** [comment]
So the atomic-site repo already has a license, MIT, which it has had since creation.  Closing this issue.
