### ISSUE TITLE
Site is down?

### ISSUE THREAD

**Issue by derekmurawsky** [projectatomic/atomic-site#597]
Trying to access the main site https://www.projectatomic.io/ (at least, where I was led by google) and am seeing an error:
![image](https://user-images.githubusercontent.com/3741839/136428974-87000905-c013-4c70-b9be-4faef7c7db63.png)

**Comment by mscherer** [comment]
Yeah, I think the project was supposed to be sunset in June. Is there a specific URL you are looking for ?

**Comment by jberkus** [comment]
Atomic Host went permanently EOL in June.  Podman and the other container tools moved to github/containers.  So ProjectAtomic is, at this point, gone.

**Comment by derekmurawsky** [comment]
I didn't realize, thanks for the information. I was looking for an open source, container optimized/native OS, and all of them seem to have been bought or closed down.

**Comment by cgwalters** [comment]
> . I was looking for an open source, container optimized/native OS, and all of them seem to have been bought or closed down.

One successor to Atomic Host is https://getfedora.org/en/coreos?stream=stable that is definitely FOSS, container optimized, and not closed down.  Hard to know exactly what you mean by "bought" but I don't think it's "bought" either.

**Comment by derekmurawsky** [comment]
> > . I was looking for an open source, container optimized/native OS, and all of them seem to have been bought or closed down.
> 
> One successor to Atomic Host is https://getfedora.org/en/coreos?stream=stable that is definitely FOSS, container optimized, and not closed down. Hard to know exactly what you mean by "bought" but I don't think it's "bought" either.

CoreOS is actually what I meant, but I didn't realize there was a fedora flavor now. Thanks!
