### ISSUE TITLE
Cockpit needs some docuentation

### ISSUE THREAD

**Issue by larsks** [projectatomic/atomic-site#80]
There doesn't appear to be any documentation at http://www.projectatomic.io/docs/gettingstarted/ or http://www.projectatomic.io/docs/cockpit/ or elsewhere with information about how to initially log in to cockpit.

**Comment by jzb** [comment]
Hey Jason - we discussed around Container.Camp - just tagging you with this one. We should maybe use F22 as a basis for this?

**Comment by jasonbrooks** [comment]
Sure, I'll work on this.

**Comment by nzwulfin** [comment]
Bumping for the move from daemon to privileged container by the cockpit team

**Comment by jasonbrooks** [comment]
I should've updated this issue, but I checked on this a few weeks back, saw the doc page at http://www.projectatomic.io/docs/cockpit/, and added some info to it w/ https://github.com/projectatomic/atomic-site/pull/222.

**Comment by jberkus** [comment]
Closing since this is all moving over to docs.projectatomic.io
