### ISSUE TITLE
SSL Error in Chrome

### ISSUE THREAD

**Issue by robszumski** [projectatomic/atomic-site#82]
Chrome is rejecting the SSL cert due to domain mismatch:

![image](https://cloud.githubusercontent.com/assets/755540/5347458/876b7bea-7edd-11e4-8b59-a3564144be72.png)

**Comment by jzb** [comment]
We're in the process of getting an SSL cert for the domain in any case. Closing this - thanks for the report.

**Comment by mscherer** [comment]
We do already have it
